import type { Metadata } from "next";
import {IBM_Plex_Sans as FontSans} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import {cn} from "@/lib/utils";
import Header from "@/components/home/header";
import { Toast} from "@/components/ui/toast";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/toaster";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Header></Header> 
       
       <main>{children}</main>
      <Toaster/>
   
    
      </body>
    </html>
  </ClerkProvider>
  );
}
